// app/components/Lightbox.vue
<script setup lang="ts">
import { useSwipe, onKeyStroke } from '@vueuse/core'
import type { ConvertedImage } from '~/types'
import { useSettingsStore } from '~/stores/settings'
import { useConverter } from '~/composables/useConverter'

const props = defineProps<{
  modelValue: boolean
  images: ConvertedImage[]
  initialIndex: number
}>()

const emit = defineEmits(['update:modelValue'])

const currentIndex = ref(props.initialIndex)
const container = ref<HTMLElement | null>(null)

// Ensure current index is valid
watch(() => props.initialIndex, (val) => {
  currentIndex.value = val
})

const currentImage = computed(() => props.images[currentIndex.value])

const formatSize = (bytes: number) => {
  if (bytes === 0) return '0 B'
  const k = 1024
  const sizes = ['B', 'KB', 'MB']
  const i = Math.floor(Math.log(bytes) / Math.log(k))
  return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
}

const settingsStore = useSettingsStore()
const { saveSingleImage } = useConverter()

const downloadLabel = computed(() => {
  return settingsStore.saveMethod === 'fs' ? 'Сохранить' : 'Скачать'
})

const downloadImage = () => {
  const img = currentImage.value
  if (img) {
    saveSingleImage(img)
  }
}

const next = () => {
  if (currentIndex.value < props.images.length - 1) {
    currentIndex.value++
  }
}

const prev = () => {
  if (currentIndex.value > 0) {
    currentIndex.value--
  }
}

const close = () => {
  emit('update:modelValue', false)
}

// Swipe support
const { lengthX, isSwiping } = useSwipe(container, {
  threshold: 10,
  passive: true
})

// UI State for animations
const isAnimating = ref(false)
const manualOffset = ref(0) // Used during the "snap" animation

// Combined offset: Drag offset (while swiping) OR Manual offset (while animating snap)
const swipeOffset = computed(() => {
  if (isSwiping.value) return -lengthX.value
  return manualOffset.value
})

const prevImage = computed(() => currentIndex.value > 0 ? props.images[currentIndex.value - 1] : null)
const nextImage = computed(() => currentIndex.value < props.images.length - 1 ? props.images[currentIndex.value + 1] : null)

watch(isSwiping, (swiping) => {
  if (swiping) {
    // Start of swipe
    manualOffset.value = 0
    isAnimating.value = false
  } else {
    // End of swipe
    const threshold = 50
    const screenWidth = container.value?.offsetWidth || window.innerWidth
    
    // Determine target
    let target = 'stay' as 'next' | 'prev' | 'stay'
    if (lengthX.value > threshold && nextImage.value) target = 'next'
    else if (lengthX.value < -threshold && prevImage.value) target = 'prev'
    
    // Animate
    isAnimating.value = true
    
    if (target === 'next') {
      manualOffset.value = -screenWidth // Animate to left (next image comes in)
      setTimeout(() => {
        next()
        resetAnimation()
      }, 300)
    } else if (target === 'prev') {
      manualOffset.value = screenWidth // Animate to right (prev image comes in)
      setTimeout(() => {
        prev()
        resetAnimation()
      }, 300)
    } else {
      manualOffset.value = 0 // Snap back
      setTimeout(() => {
        resetAnimation()
      }, 300)
    }
  }
})

const resetAnimation = () => {
    isAnimating.value = false
    manualOffset.value = 0
}

// Keyboard support
onKeyStroke('ArrowRight', (e) => {
  e.preventDefault()
  next()
})
onKeyStroke('ArrowLeft', (e) => {
  e.preventDefault()
  prev()
})
onKeyStroke('Escape', (e) => {
  e.preventDefault()
  close()
})
</script>

<template>
  <div class="fixed inset-0 z-50 bg-black flex flex-col items-center justify-center">
    <!-- Close button -->
    <button 
      class="absolute top-4 right-4 z-50 p-3 rounded-full bg-black/20 hover:bg-white/10 text-white backdrop-blur-md transition-colors"
      @click.stop="close"
    >
      <UIcon name="i-heroicons-x-mark" class="w-6 h-6" />
    </button>

    <!-- Main Image Container -->
    <div 
      ref="container" 
      class="relative w-full h-full flex items-center justify-center overflow-hidden touch-none"
      :class="{ 'pointer-events-none': isAnimating }"
    >
      <!-- Previous Image -->
      <div 
        v-if="prevImage"
        class="absolute inset-0 flex items-center justify-center will-change-transform"
        :class="{ 'transition-transform duration-300 ease-out': isAnimating }"
        :style="{ transform: `translateX(calc(-100% + ${swipeOffset}px))` }"
      >
        <img :src="prevImage.url" class="max-w-full max-h-full object-contain select-none pointer-events-none" />
      </div>

      <!-- Current Image -->
      <div 
        v-if="currentImage"
        class="absolute inset-0 flex items-center justify-center will-change-transform"
        :class="{ 'transition-transform duration-300 ease-out': isAnimating }"
        :style="{ transform: `translateX(${swipeOffset}px)` }"
      >
        <img :src="currentImage.url" class="max-w-full max-h-full object-contain select-none pointer-events-none" />
      </div>

      <!-- Next Image -->
      <div 
        v-if="nextImage"
        class="absolute inset-0 flex items-center justify-center will-change-transform"
        :class="{ 'transition-transform duration-300 ease-out': isAnimating }"
        :style="{ transform: `translateX(calc(100% + ${swipeOffset}px))` }"
      >
        <img :src="nextImage.url" class="max-w-full max-h-full object-contain select-none pointer-events-none" />
      </div>
    </div>

    <!-- Navigation Buttons (Desktop) -->
    <button
      v-if="currentIndex > 0"
      class="absolute left-4 top-1/2 -translate-y-1/2 hidden md:flex p-4 rounded-full bg-black/20 hover:bg-white/10 text-white backdrop-blur-md transition-all active:scale-95"
      @click.stop="prev"
    >
      <UIcon name="i-heroicons-chevron-left" class="w-8 h-8" />
    </button>

    <button
      v-if="currentIndex < images.length - 1"
      class="absolute right-4 top-1/2 -translate-y-1/2 hidden md:flex p-4 rounded-full bg-black/20 hover:bg-white/10 text-white backdrop-blur-md transition-all active:scale-95"
      @click.stop="next"
    >
      <UIcon name="i-heroicons-chevron-right" class="w-8 h-8" />
    </button>

    <!-- Info Bar -->
    <div class="absolute bottom-6 inset-x-0 mx-auto w-[90%] max-w-lg bg-black/60 backdrop-blur-xl rounded-2xl p-4 text-white flex justify-between items-center shadow-2xl ring-1 ring-white/10">
      <div class="flex flex-col min-w-0 pr-4">
        <span class="font-medium truncate text-sm sm:text-base">{{ currentImage?.originalName }}</span>
        <div class="flex items-center gap-2 text-xs text-gray-300">
           <span>{{ formatSize(currentImage?.originalSize || 0) }}</span>
           <UIcon name="i-heroicons-arrow-right" class="w-3 h-3 text-gray-500" />
           <span class="text-green-400 font-bold">{{ formatSize(currentImage?.convertedSize || 0) }}</span>
        </div>
      </div>
      
      <UButton 
        icon="i-heroicons-arrow-down-tray"
        color="primary"
        variant="solid"
        size="md"
        class="shrink-0 rounded-lg font-bold"
        :label="downloadLabel"
        @click="downloadImage"
      />
    </div>
  </div>
</template>

// components/Lightbox.tsx
import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { X, ChevronLeft, ChevronRight, Download, Smartphone } from 'lucide-react';
import { ConvertedImage, SaveMethod } from '../types';
import { Button } from './Button';

interface LightboxProps {
  images: ConvertedImage[];
  initialIndex: number;
  isOpen: boolean;
  onClose: () => void;
  onSave: (image: ConvertedImage) => void;
  saveMethod: SaveMethod;
}

const formatBytes = (bytes: number, decimals = 2) => {
  if (!+bytes) return '0 Bytes';
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ['Б', 'КБ', 'МБ', 'ГБ'];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / Math.pow(k, i)).toFixed(dm))} ${sizes[i]}`;
};

export const Lightbox: React.FC<LightboxProps> = ({
  images,
  initialIndex,
  isOpen,
  onClose,
  onSave,
  saveMethod,
}) => {
  const [index, setIndex] = useState(initialIndex);
  const [direction, setDirection] = useState(0);

  useEffect(() => {
    if (isOpen) {
      setIndex(initialIndex);
      setDirection(0); // Reset direction on open to trigger "zoom" instead of "slide"
    }
  }, [isOpen, initialIndex]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!isOpen) return;
      if (e.key === 'ArrowLeft') paginate(-1);
      if (e.key === 'ArrowRight') paginate(1);
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, index]);

  const paginate = (newDirection: number) => {
    const newIndex = index + newDirection;
    if (newIndex >= 0 && newIndex < images.length) {
      setDirection(newDirection);
      setIndex(newIndex);
    }
  };

  const currentImage = images[index];

  // Animation Variants
  const variants = {
    enter: (direction: number) => {
      // If direction is 0, it means we just opened the lightbox -> Zoom In
      if (direction === 0) {
        return { opacity: 0, scale: 0.8, x: 0 };
      }
      // Otherwise -> Slide In
      return {
        x: direction > 0 ? 1000 : -1000,
        opacity: 0,
        scale: 1,
      };
    },
    center: {
      zIndex: 1,
      x: 0,
      opacity: 1,
      scale: 1,
    },
    exit: (direction: number) => {
      // If closing (we'd need to pass a closing prop, but strictly here for slide out)
      // We keep slide out logic for navigation
      return {
        zIndex: 0,
        x: direction < 0 ? 1000 : -1000,
        opacity: 0,
        scale: 1,
      };
    },
  };

  const swipeConfidenceThreshold = 10000;
  const swipePower = (offset: number, velocity: number) => {
    return Math.abs(offset) * velocity;
  };

  return (
    <AnimatePresence>
      {isOpen && currentImage && (
        <motion.div
          initial={{ opacity: 0, backdropFilter: "blur(0px)" }}
          animate={{ opacity: 1, backdropFilter: "blur(20px)" }}
          exit={{ opacity: 0, backdropFilter: "blur(0px)" }}
          transition={{ duration: 0.3 }}
          className="fixed inset-0 z-50 bg-black/90 flex flex-col justify-between"
        >
          {/* Header */}
          <div className="absolute top-0 left-0 right-0 z-20 p-4 flex justify-between items-center bg-gradient-to-b from-black/80 to-transparent pointer-events-none">
            <div className="text-white text-sm font-medium drop-shadow-md px-3 py-1 bg-white/10 rounded-full border border-white/5 backdrop-blur-md">
              {index + 1} / {images.length}
            </div>
            <div className="pointer-events-auto">
                <Button variant="ghost" size="icon" onClick={onClose} className="text-white hover:bg-white/20 rounded-full">
                <X size={28} />
                </Button>
            </div>
          </div>

          {/* Main Content */}
          <div className="flex-1 relative flex items-center justify-center overflow-hidden w-full h-full">
            <AnimatePresence initial={true} custom={direction} mode="popLayout">
              <motion.img
                key={currentImage.id}
                src={currentImage.url}
                custom={direction}
                variants={variants}
                initial="enter"
                animate="center"
                exit="exit"
                transition={{
                  x: { type: 'spring', stiffness: 300, damping: 30 },
                  opacity: { duration: 0.2 },
                  scale: { duration: 0.3, type: "spring" } // Smooth zoom
                }}
                drag="x"
                dragConstraints={{ left: 0, right: 0 }}
                dragElastic={1}
                onDragEnd={(e, { offset, velocity }) => {
                  const swipe = swipePower(offset.x, velocity.x);
                  if (swipe < -swipeConfidenceThreshold) {
                    paginate(1);
                  } else if (swipe > swipeConfidenceThreshold) {
                    paginate(-1);
                  }
                }}
                className="absolute max-w-[95%] max-h-[90%] object-contain pointer-events-auto cursor-grab active:cursor-grabbing shadow-2xl drop-shadow-2xl"
                alt={currentImage.originalName}
              />
            </AnimatePresence>

            {/* Nav Buttons (Desktop) */}
            {index > 0 && (
              <button
                className="absolute left-4 z-10 p-3 bg-black/20 hover:bg-black/50 border border-white/10 backdrop-blur-sm rounded-full text-white hidden md:flex transition-all hover:scale-110 active:scale-95"
                onClick={() => paginate(-1)}
              >
                <ChevronLeft size={32} />
              </button>
            )}
            {index < images.length - 1 && (
              <button
                className="absolute right-4 z-10 p-3 bg-black/20 hover:bg-black/50 border border-white/10 backdrop-blur-sm rounded-full text-white hidden md:flex transition-all hover:scale-110 active:scale-95"
                onClick={() => paginate(1)}
              >
                <ChevronRight size={32} />
              </button>
            )}
          </div>

          {/* Footer Actions */}
          <div className="z-20 p-6 bg-gradient-to-t from-black via-black/80 to-transparent flex flex-col items-center justify-center pb-10 gap-5">
            
            {/* Size Info Badge */}
            <div className="flex items-center gap-3 text-sm font-medium bg-zinc-900/80 px-5 py-2.5 rounded-2xl backdrop-blur-md border border-zinc-700/50 shadow-xl">
                <span className="text-zinc-400">{formatBytes(currentImage.originalSize || 0)}</span>
                <span className="text-zinc-600">→</span>
                <span className="text-primary font-bold">{formatBytes(currentImage.size)}</span>
            </div>

            <Button
              variant="primary"
              size="lg"
              className="shadow-[0_0_20px_rgba(139,92,246,0.2)] min-w-[200px] rounded-2xl"
              onClick={() => onSave(currentImage)}
            >
              {saveMethod === SaveMethod.BROWSER_DOWNLOAD ? <Download className="mr-2" size={20} /> : <Smartphone className="mr-2" size={20} />}
              Сохранить
            </Button>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};
